version: '3.1'
services:
    postgres:
        image: postgres:11.4
        ports:
            - "15433:5432"
        container_name: demo.postgres
        environment:
            POSTGRES_PASSWORD: demopass
            POSTGRES_USER: demouser
            POSTGRES_DB: demoDb
        hostname: postgres
        restart: always

    pgadmin4:
        image: dpage/pgadmin4:latest
        container_name: pgadmin4
        ports:
            - 8001:80
        volumes:
            - ./pgadmin:/var/demo/pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin
            PGADMIN_DEFAULT_PASSWORD: pgadmin
        hostname: pgadmin4
        depends_on:
            - postgres
        restart: always
