name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.1
    - name: Run build
      run: |
        sudo chmod +x ./gradlew
        ./gradlew build
    - name: Run test
      run: ./gradlew clean test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cp /demo/build/libs/demo-0.0.1-SNAPSHOT.jar /deploy/
          cd deploy
          jar demo.zip *
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}   # optional: defaults to us-east-1
