name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.1
    - name: Run build
      run: |
        sudo chmod +x ./gradlew
        ./gradlew build
    - name: Run test
      run: ./gradlew clean test
